<a href="https://colab.research.google.com/github/Cairo-Lopes/pyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


In [2]:
## introdution to tensors

## creating tensors


In [3]:
# scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

### Random tensors

Why random tensors?
- Random tensors are important because the way many neural networks learn is that start with tensor full of random number adjust those random numbers to better represent the data
Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#random_tensor = torch.rand(3,4)
random_tensor = torch.rand(1,10,6)
random_tensor

tensor([[[6.2833e-02, 7.9900e-01, 8.1623e-01, 8.9532e-01, 7.4583e-01,
          1.8113e-02],
         [6.4037e-01, 9.2332e-01, 2.0328e-01, 2.4182e-04, 3.9488e-01,
          7.0001e-01],
         [3.9682e-01, 4.0004e-01, 1.7070e-01, 5.8284e-01, 9.8230e-02,
          8.5224e-01],
         [8.0387e-02, 6.7772e-01, 3.7350e-01, 5.1083e-01, 7.5014e-01,
          3.7179e-01],
         [7.6235e-01, 2.8138e-01, 3.8674e-02, 8.7449e-01, 6.0145e-01,
          7.2660e-01],
         [7.1863e-01, 8.8655e-01, 4.7407e-01, 7.6162e-01, 9.2186e-01,
          8.1365e-03],
         [5.4300e-01, 3.5592e-01, 3.0677e-01, 1.1924e-02, 8.5011e-01,
          1.9251e-01],
         [8.6523e-01, 8.6607e-01, 1.6732e-01, 1.2144e-01, 8.4513e-01,
          4.1413e-01],
         [2.8715e-01, 2.1804e-01, 3.6277e-01, 7.4509e-01, 6.6181e-01,
          9.2692e-01],
         [6.9431e-01, 9.2650e-01, 6.2164e-01, 1.4966e-01, 8.3907e-01,
          6.9940e-01]]])

In [27]:
# create a rendom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [32]:
# tensors with zeros and ones
# all zeros
zeros = torch.zeros(1, 4 , 4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
# all ones
ones = torch.ones(1, 4, 4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [41]:
# range of range and tensors-like
# torch.range()
arange = torch.arange(start=0, end=100, step=2)
arange

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
# tensors like
likes = torch.zeros_like(input=arange)
likes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])