## 00. PyTorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


In [2]:
## introdution to tensors

## creating tensors


In [3]:
# scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

### Random tensors

Why random tensors?
- Random tensors are important because the way many neural networks learn is that start with tensor full of random number adjust those random numbers to better represent the data
Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#random_tensor = torch.rand(3,4)
random_tensor = torch.rand(1,10,6)
random_tensor

tensor([[[6.2833e-02, 7.9900e-01, 8.1623e-01, 8.9532e-01, 7.4583e-01,
          1.8113e-02],
         [6.4037e-01, 9.2332e-01, 2.0328e-01, 2.4182e-04, 3.9488e-01,
          7.0001e-01],
         [3.9682e-01, 4.0004e-01, 1.7070e-01, 5.8284e-01, 9.8230e-02,
          8.5224e-01],
         [8.0387e-02, 6.7772e-01, 3.7350e-01, 5.1083e-01, 7.5014e-01,
          3.7179e-01],
         [7.6235e-01, 2.8138e-01, 3.8674e-02, 8.7449e-01, 6.0145e-01,
          7.2660e-01],
         [7.1863e-01, 8.8655e-01, 4.7407e-01, 7.6162e-01, 9.2186e-01,
          8.1365e-03],
         [5.4300e-01, 3.5592e-01, 3.0677e-01, 1.1924e-02, 8.5011e-01,
          1.9251e-01],
         [8.6523e-01, 8.6607e-01, 1.6732e-01, 1.2144e-01, 8.4513e-01,
          4.1413e-01],
         [2.8715e-01, 2.1804e-01, 3.6277e-01, 7.4509e-01, 6.6181e-01,
          9.2692e-01],
         [6.9431e-01, 9.2650e-01, 6.2164e-01, 1.4966e-01, 8.3907e-01,
          6.9940e-01]]])

In [27]:
# create a rendom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [32]:
# tensors with zeros and ones
# all zeros
zeros = torch.zeros(1, 4 , 4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
# all ones
ones = torch.ones(1, 4, 4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [41]:
# range of range and tensors-like
# torch.range()
arange = torch.arange(start=0, end=100, step=2)
arange

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
# tensors like
likes = torch.zeros_like(input=arange)
likes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Dealing with tensor data types

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with
PyTorch & deep learing:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

https://pytorch.org/docs/stable/tensors.html

In [48]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.4, 3.5, 6.5],
                               dtype=None, # what datatype is the tensor (float32, float 16)
                               device=None,# what device is yout tensor on
                               requires_grad=False, # whether or not to track gradients with this tensor operations.
                               )
float_32_tensor, float_32_tensor.dtype

(tensor([3.4000, 3.5000, 6.5000]), torch.float32)

In [47]:
# float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.4004, 3.5000, 6.5000], dtype=torch.float16)

### getting tensor attributes

  1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
  2. Tensors not right shape - to get a shape  from a tensor, can use `tensor.shape`
  3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [49]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [50]:
# Find out details about some tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.5131, 0.1233, 0.9871, 0.9099],
        [0.3882, 0.1737, 0.2579, 0.2141],
        [0.1529, 0.2013, 0.1467, 0.5875]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Subtraction
* Mutiplication (element-wise)
* Division
* Matrix multiplication

In [51]:
# TENSOR + 10
torch.tensor([1, 2, 3]) + 10

tensor([11, 12, 13])

In [52]:
# TENSOR * 10
torch.tensor([1, 2, 3]) * 10

tensor([10, 20, 30])

In [53]:
# TENSOR - 10
torch.tensor([1, 2, 3]) - 10

tensor([-9, -8, -7])

In [54]:
# TENSOR / 10
torch.tensor([1, 2, 3]) / 10

tensor([0.1000, 0.2000, 0.3000])

In [56]:
# Try out PyTorch in-built functions
print(torch.mul(torch.tensor([1, 2, 3]), 10))
print(torch.add(torch.tensor([1, 2, 3]), 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product) -  ***a* • *b***

More info: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mult. need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`


In [74]:
# element wise multiplication
TENSOR = torch.tensor([1, 2, 3])
print(TENSOR, "*", TENSOR)
print(f"Equals: {TENSOR * TENSOR}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [73]:
# matrix mult
torch.matmul(TENSOR, TENSOR)

tensor(14)

In [81]:
%%time
print(TENSOR @ TENSOR)

tensor(14)
CPU times: user 527 µs, sys: 0 ns, total: 527 µs
Wall time: 535 µs


In [77]:
%%time
value = 0
for i in range(len(TENSOR)):
  value += TENSOR[i] * TENSOR[i]
print(value)

tensor(14)
CPU times: user 1.39 ms, sys: 24 µs, total: 1.42 ms
Wall time: 1.44 ms


In [78]:
%%time
torch.matmul(TENSOR, TENSOR)

CPU times: user 74 µs, sys: 5 µs, total: 79 µs
Wall time: 84.4 µs


tensor(14)